"""
Report Generator - HTML/PDF
Creates a reader-friendly HTML report from the trend analysis.
"""
import json
from datetime import datetime
from pathlib import Path

from rich.console import Console

from config import TMP_DIR, TrendReport, get_reports_dir

console = Console()

HTML_TEMPLATE = """
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Vibe-Coding Trend Report - {date}</title>
    <style>
        body {{ font-family: 'Inter', sans-serif; line-height: 1.6; color: #333; max-width: 800px; margin: 0 auto; padding: 20px; }}
        h1 {{ color: #2563eb; border-bottom: 2px solid #eee; padding-bottom: 10px; }}
        h2 {{ color: #1e40af; margin-top: 30px; }}
        .summary-box {{ background: #f0f9ff; padding: 15px; border-radius: 8px; border-left: 4px solid #2563eb; font-style: italic; }}
        .opp-card {{ border: 1px solid #e5e7eb; border-radius: 8px; padding: 20px; margin-bottom: 20px; box-shadow: 0 2px 4px rgba(0,0,0,0.05); }}
        .opp-header {{ display: flex; justify-content: space-between; align-items: center; border-bottom: 1px solid #eee; padding-bottom: 10px; margin-bottom: 10px; }}
        .rank {{ background: #2563eb; color: white; padding: 5px 10px; border-radius: 20px; font-weight: bold; font-size: 0.9em; }}
        .score {{ color: #16a34a; font-weight: bold; }}
        .meta {{ font-size: 0.85em; color: #666; margin-top: 5px; }}
        .tag {{ background: #eee; padding: 2px 6px; border-radius: 4px; font-size: 0.8em; margin-right: 5px; }}
        a {{ color: #2563eb; text-decoration: none; }}
        a:hover {{ text-decoration: underline; }}
        @media print {{
            body {{ max-width: 100%; }}
            .opp-card {{ break-inside: avoid; }}
        }}
    </style>
</head>
<body>
    <h1>🚀 Vibe-Coding Trend Report</h1>
    <p><strong>Generated:</strong> {generated_at} | <strong>Week:</strong> {week_range}</p>
    
    <div class="summary-box">
        {summary}
    </div>

    <h2>🔥 Top Opportunities</h2>
    {opportunities}

    <h2>📈 Emerging Patterns</h2>
    <ul>
        {patterns}
    </ul>

    <hr>
    <p style="text-align: center; color: #888; font-size: 0.8em;">
        Generated by Vibe-Coding Scraper • {year}
    </p>
</body>
</html>
"""

OPP_TEMPLATE = """
    <div class="opp-card">
        <div class="opp-header">
            <span class="rank">#{rank}</span>
            <span class="score">Vibe Score: {score}/10</span>
        </div>
        <h3><a href="{url}" target="_blank">{name}</a></h3>
        <p>{description}</p>
        <p><strong>💡 Why Vibe-Codeable:</strong> {reason}</p>
        <div class="meta">
            <span class="tag">⏱️ {time}</span>
            <span class="tag">📍 {source}</span>
        </div>
    </div>
"""

def generate_html_report(report: TrendReport, analysis: dict) -> Path:
    """Generate HTML report from trend data."""
    console.print("[bold blue]📄 Generating HTML Report...[/]")
    
    date_str = datetime.now().strftime("%Y-%m-%d")
    year = datetime.now().year
    
    # Format Opportunities
    opps_html = ""
    for opp in report.top_opportunities:
        opps_html += OPP_TEMPLATE.format(
            rank=opp.get("rank"),
            score=opp.get("vibe_score"),
            name=opp.get("name"),
            url=opp.get("url", "#"),
            description=opp.get("description"),
            reason=opp.get("why_vibe_codeable"),
            time=opp.get("estimated_build_time", "N/A"),
            source=opp.get("source", "Unknown")
        )
    
    # Format Patterns
    patterns_html = ""
    for pat in analysis.get("emerging_patterns", []):
        patterns_html += f"<li><strong>{pat.get('pattern')}:</strong> {pat.get('description')}</li>"

    html_content = HTML_TEMPLATE.format(
        date=date_str,
        generated_at=datetime.now().strftime("%Y-%m-%d %H:%M"),
        week_range=f"{report.week_start.strftime('%b %d')} - {report.week_end.strftime('%b %d')}",
        summary=report.ai_summary,
        opportunities=opps_html,
        patterns=patterns_html,
        year=year
    )
    
    output_path = get_reports_dir() / f"report_{datetime.now().strftime('%Y%m%d')}.html"
    
    with open(output_path, "w", encoding="utf-8") as f:
        f.write(html_content)
        
    console.print(f"[green]✓ Report generated: {output_path}[/]")
    return output_path

def main():
    today = datetime.now().strftime("%Y%m%d")
    report_path = get_reports_dir() / f"trend_report_{today}.json"
    analysis_path = get_reports_dir() / f"analysis_{today}.json"
    
    if not report_path.exists():
        console.print("[yellow]No report found.[/]")
        return
        
    with open(report_path, "r") as f:
        report = TrendReport(**json.load(f))
    with open(analysis_path, "r") as f:
        analysis = json.load(f)
        
    generate_html_report(report, analysis)

if __name__ == "__main__":
    main()
