"""
Email Delivery - SMTP/Gmail

Sends weekly digest email with top vibe-coding opportunities.
Uses Gmail SMTP with App Password.
"""
import asyncio
import json
import smtplib
from datetime import datetime
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText
from pathlib import Path

from rich.console import Console

from config import TMP_DIR, get_env, TrendReport

console = Console()


def create_email_html(report: TrendReport, analysis: dict, sheet_url: str | None) -> str:
    """Create HTML email content."""
    
    # Top opportunities
    opportunities_html = ""
    for opp in analysis.get("top_opportunities", [])[:10]:
        opportunities_html += f"""
        <tr>
            <td style="padding: 12px; border-bottom: 1px solid #eee;">
                <strong>#{opp.get('rank', '?')} {opp.get('name', 'Unknown')}</strong>
                <br>
                <span style="color: #666; font-size: 14px;">
                    Score: <strong style="color: #10b981;">{opp.get('vibe_score', '?')}/10</strong> | 
                    Build time: {opp.get('estimated_build_time', '?')}
                </span>
                <br>
                <span style="color: #888; font-size: 13px;">{opp.get('why_vibe_codeable', '')[:150]}</span>
                <br>
                <a href="{opp.get('url', '#')}" style="color: #3b82f6; font-size: 13px;">View source →</a>
            </td>
        </tr>
        """
    
    # Categories
    categories = ", ".join(report.trending_categories[:8])
    
    # Service as Software ideas
    service_ideas_html = ""
    for idea in analysis.get("service_as_software_ideas", [])[:5]:
        service_ideas_html += f"""
        <li style="margin-bottom: 8px;">
            <strong>{idea.get('service', '')}</strong> → {idea.get('software_opportunity', '')}
            <span style="color: #888;">({idea.get('complexity', '')} complexity)</span>
        </li>
        """
    
    sheet_link = f'<a href="{sheet_url}" style="color: #3b82f6;">View in Google Sheets →</a>' if sheet_url else ""
    
    html = f"""
    <!DOCTYPE html>
    <html>
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
    </head>
    <body style="font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif; max-width: 600px; margin: 0 auto; padding: 20px; background: #f9fafb;">
        <div style="background: white; border-radius: 12px; padding: 24px; box-shadow: 0 1px 3px rgba(0,0,0,0.1);">
            
            <h1 style="color: #111; margin-bottom: 8px;">🚀 Weekly Vibe-Coding Digest</h1>
            <p style="color: #666; margin-top: 0;">
                {report.week_start.strftime('%b %d')} - {report.week_end.strftime('%b %d, %Y')} | 
                {report.total_items} items analyzed
            </p>
            
            <div style="background: #f0fdf4; border-left: 4px solid #10b981; padding: 16px; margin: 20px 0; border-radius: 4px;">
                <strong style="color: #059669;">📝 This Week's Summary</strong>
                <p style="color: #374151; margin: 8px 0 0 0;">{analysis.get('summary', 'No summary available')}</p>
            </div>
            
            <h2 style="color: #111; margin-top: 24px;">🔥 Trending Categories</h2>
            <p style="color: #666;">{categories}</p>
            
            <h2 style="color: #111; margin-top: 24px;">🎯 Top Vibe-Coding Opportunities</h2>
            <p style="color: #888; font-size: 14px;">Scored by AI for solo developer potential</p>
            
            <table style="width: 100%; border-collapse: collapse;">
                {opportunities_html}
            </table>
            
            <h2 style="color: #111; margin-top: 24px;">💡 Service-as-Software Ideas</h2>
            <p style="color: #888; font-size: 14px;">Traditional services that AI can replace</p>
            <ul style="color: #374151;">
                {service_ideas_html}
            </ul>
            
            <div style="margin-top: 32px; padding-top: 20px; border-top: 1px solid #eee; text-align: center;">
                {sheet_link}
                <p style="color: #888; font-size: 13px; margin-top: 16px;">
                    Generated by Vibe-Coding Trend Scraper<br>
                    Data from Product Hunt, Indie Hackers, Acquire, Reddit, HN, Bluesky
                </p>
            </div>
            
        </div>
    </body>
    </html>
    """
    
    return html


def create_email_text(report: TrendReport, analysis: dict) -> str:
    """Create plain text email content."""
    
    lines = [
        "🚀 WEEKLY VIBE-CODING DIGEST",
        f"Week of {report.week_start.strftime('%b %d')} - {report.week_end.strftime('%b %d, %Y')}",
        f"Items analyzed: {report.total_items}",
        "",
        "📝 SUMMARY",
        analysis.get("summary", ""),
        "",
        "🔥 TRENDING CATEGORIES",
        ", ".join(report.trending_categories[:8]),
        "",
        "🎯 TOP VIBE-CODING OPPORTUNITIES",
        "",
    ]
    
    for opp in analysis.get("top_opportunities", [])[:10]:
        lines.extend([
            f"#{opp.get('rank', '?')} {opp.get('name', 'Unknown')}",
            f"   Score: {opp.get('vibe_score', '?')}/10 | Build time: {opp.get('estimated_build_time', '?')}",
            f"   {opp.get('why_vibe_codeable', '')}",
            f"   {opp.get('url', '')}",
            "",
        ])
    
    lines.extend([
        "",
        "💡 SERVICE-AS-SOFTWARE IDEAS",
        "",
    ])
    
    for idea in analysis.get("service_as_software_ideas", [])[:5]:
        lines.append(f"• {idea.get('service', '')} → {idea.get('software_opportunity', '')}")
    
    return "\n".join(lines)


async def send_email(
    report: TrendReport, 
    analysis: dict, 
    sheet_url: str | None = None
) -> bool:
    """
    Send weekly digest email.
    
    Args:
        report: TrendReport object
        analysis: Raw analysis dict
        sheet_url: Optional Google Sheets URL
        
    Returns:
        True if sent successfully
    """
    console.print("[bold blue]📧 Sending weekly digest email...[/]")
    
    smtp_host = get_env("SMTP_HOST", "smtp.gmail.com")
    smtp_port = int(get_env("SMTP_PORT", "587"))
    smtp_user = get_env("SMTP_USER", required=True)
    smtp_password = get_env("SMTP_PASSWORD", required=True)
    recipient = get_env("EMAIL_RECIPIENT", smtp_user)
    
    # Create message
    msg = MIMEMultipart("alternative")
    msg["Subject"] = f"🚀 Vibe-Coding Digest - Week of {report.week_end.strftime('%b %d')}"
    msg["From"] = smtp_user
    msg["To"] = recipient
    
    # Attach plain text and HTML versions
    text_content = create_email_text(report, analysis)
    html_content = create_email_html(report, analysis, sheet_url)
    
    msg.attach(MIMEText(text_content, "plain"))
    msg.attach(MIMEText(html_content, "html"))
    
    # Send
    try:
        with smtplib.SMTP(smtp_host, smtp_port) as server:
            server.starttls()
            server.login(smtp_user, smtp_password)
            server.send_message(msg)
        
        console.print(f"[green]✓ Email sent to {recipient}[/]")
        return True
        
    except Exception as e:
        console.print(f"[red]Failed to send email: {e}[/]")
        return False


async def main():
    """Run email sender."""
    # Load latest report
    today = datetime.now().strftime("%Y%m%d")
    report_path = TMP_DIR / f"trend_report_{today}.json"
    analysis_path = TMP_DIR / f"analysis_{today}.json"
    
    if not report_path.exists():
        console.print("[yellow]No report found. Run analyzer first.[/]")
        return False
    
    with open(report_path, "r") as f:
        report_data = json.load(f)
        report = TrendReport(**report_data)
    
    with open(analysis_path, "r") as f:
        analysis = json.load(f)
    
    return await send_email(report, analysis)


if __name__ == "__main__":
    asyncio.run(main())
